apiVersion: v1
kind: Service
metadata:
  name: swishtest
  labels:
    app: swishtest
spec:
  type: NodePort #Exposes the service as a node ports
  ports:
    - port: 22
      name: ssh
      protocol: TCP
      targetPort: 22
      nodePort: 30043
  selector:
    app: swishtest